spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #服务发现组件结合,通过 serviceId 转发到具体的服务实例
          enabled: true
      routes:
          #网关路由USER-SERVICE服务,使用 Spring Cloud Gateway的默认路由规则大写的serviceId/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
          - Path=/USER-SERVICE/**

server:
  port: 9300

management:
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug