spring:
  application:
    name: order-service

server:
  port: 9120

eureka:
  client:
    #在此指定服务注册中心地址
    service-url:
      defaultZone: http://localhost:8080/eureka/
  client:
    # 开启健康检查（需要spring-boot-starter-actuator依赖）
    healthcheck:
      enabled: true
  instance:
    #续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 30
    #续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10


