spring:
  application:
    name: hystrix-turbine-amqp

  rabbitmq:
    addresses: 192.168.10.100
    port: 15672
    username: admin
    password: 12345


server:
  port: 9260

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
