spring:
  application:
    name: zuul-gateway

server:
  port: 9310

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

zuul:
  # 前缀 版本号
  prefix: /v1
  routes:
    # http://localhost:9310/v1/user/
    user-api:
      path: /user/**
      # 服务id
      serviceId: user-service

logging:
  level:
    com.netflix: debug
