spring:
  application:
    name: security-oauth2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.253:3306/spring?useSSL=false
    username: test
    password: 123456
  redis:
    host: 192.168.10.253
    port: 6379
    password: 123456

server:
  port: 9400

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/